### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Kubuxu** [matishsiao/goInfo#1]
Hello, I would like to use your code in IPFS project but I am not sure if current copyright allows me for that.

It would be best if the piece of software was published either under BSD or MIT license.

Thanks.

**Comment by matishsiao** [comment]
please go ahead, it's open for everyone.

**Comment by maoueh** [comment]
@matishsiao Any news for this licensing thing, would be really great to take 2 minutes to look at #4 and merged if it's all good with you.

You have the leanest package to detect distribution, it would make it much easier if the license was included in the repository directly instead of being implicit.
